### ISSUE TITLE
The value of input is changed... Weird

### ISSUE THREAD

**Issue by nguyentienthanh812** [UMMISCO/kendrick#46] opened 2017-07-25 12:54 UTC
When I execute a model like this:

```Smalltalk
modelRK4SolverOnSIRDemoMultiConcerns
	"self new modelRK4SolverOnSIRDemoMultiConcerns"
	| model|
        model := KEModel new population: (KEPopulation size: 10000).
	model attributes: {(#status->#(#S #I #R))}.

	model atParameter: #gamma assignValue: #(#(5 1)).
		
	model atParameter: #beta assignValue: #(#(4 4)) .

	model atParameter: #mu assignValue: #(#(1  2)).
	
         model atCompartment: {#status->#S}
             put: #(#(4975 4975)).
          model atCompartment: {#status->#I}
             put: #(#(25 25)).
          model atCompartment: {#status->#R}
             put: #(#(0 0)).
	
	model
     atParameter: #i assignValue: (1 to: 2).
	^model.
```

The input of this statement: 
	```model atParameter: #gamma assignValue: #(#(5 1)).```
Always be changed from #(#(5 1)) to #(#(80 16)).
Is it a bug of Pharo? :(
![untitled](https://user-images.githubusercontent.com/30106741/28572542-b116aca6-7171-11e7-8ed1-34c4ba59f466.png)

**Comment by SergeStinckwich** [comment] 2017-07-25 13:25
I could not replicate your problem because when I run your model, I have an error ...
I think this is not a Pharo problem, but a problem from your code :-)

**Comment by nguyentienthanh812** [comment] 2017-07-25 13:30
I run my model and dont have any error :) 
But the value of parameter named "gamma" is not expected.
Can you send me your error?

**Comment by SergeStinckwich** [comment] 2017-07-25 13:56
Error: Instance of Array does not understand #ifTrue: 

Try to use same version than me : 614

**Comment by btmanh** [comment] 2017-07-25 15:30
i cannot reproduce the bug either.
Note that the value of a compartment should be a number. When an user
specify a value for a compartment, Kendrick will check if the input number
is greater than the population size (if true ==> report a warning to users).
So in the script, I have error with the method KEModel>>atCompartment:put
when the input value is an array as you did.
When I just check the parameters of the model (after commenting all
specifications of compartments), i see that the model and its parameters
work as expected.

**Comment by nguyentienthanh812** [comment] 2017-07-26 10:59
I found it. My Pharo is out of date (too old) T.T
I have updated Pharo and edited the mode. It run correctly :-)

**Comment by SergeStinckwich** [comment] 2017-07-26 11:00
which version of Pharo you use ?
So we can close this issue ?

**Comment by nguyentienthanh812** [comment] 2017-07-26 11:20
When I check System>About, it says Pharo 6.0, with the latest update: #60510. But I downloaded Pharo6.1-win.zip from the website.
There is still no Pharo version 6.1 64bit but iOS and Linux. My laptop is Windows 10 and 64 bit.

**Comment by nguyentienthanh812** [comment] 2017-07-26 14:54
Sorry, something still wrong. Can you let me check this issue again? :(

**Comment by nguyentienthanh812** [comment] 2017-07-26 15:07
Still happened. My model now is:
modelRK4SolverOnSIRDemoMultiConcerns
	"self new modelRK4SolverOnSIRDemoMultiConcerns"
	| model|
        model := KEModel new population: (KEPopulation size: 10000).
	model attributes: { #status->#(S I R). #species->#(human bird) }.

	model atParameter: #gamma assignValue: #(5 1).
		
	model atParameter: #beta assignValue: #(4 4) .

	model atParameter: #mu assignValue: #(1  2).
	
   "model atCompartment: {#status->#S}
             put: #(4975 4975).
   model atCompartment: {#status->#I}
             put: #(25 25).
   model atCompartment: {#status->#R}
             put: #(0 0)."
	model atCompartment: { #status->#S. #species->#human } put: 4975.
	model atCompartment: { #status->#I. #species->#human } put: 25.
	model atCompartment: { #status->#R. #species->#human } put: 0.
			
	model atCompartment: { #status->#S. #species->#bird } put: 4975.
	model atCompartment: { #status->#I. #species->#bird } put: 25.
	model atCompartment: { #status->#R. #species->#bird } put: 0.
			
	model
     atParameter: #i assignValue: (1 to: 2).
	^model.
==================================
When I debug, I see: 
![untitled](https://user-images.githubusercontent.com/30106741/28628400-bb66e13e-724e-11e7-8697-c202af1353dd.png)

**Comment by SergeStinckwich** [comment] 2017-07-26 15:23
I still see a lot of deleted class in your commit ... Can you fix that ?

**Comment by nguyentienthanh812** [comment] 2017-07-26 23:46
Yes, let me fix it.

**Comment by nguyentienthanh812** [comment] 2017-07-27 12:44
Now the issue 41 is fixed. It happens because I don't install Moose correctly and, additional, there is a bug in my code as well.

I fix. However, whenever I save a method, Moose automatically edits it, changes all temporary variables and deletes all comments. T.T >"<

**Comment by nguyentienthanh812** [comment] 2017-07-28 02:32
Awesome, I fix. 

"Moose automatically edits method, renames all temporary variables and deletes all comments. "
=> Because I dont copy Pharov60.sources. After copied, its fine.

We can close this issue! ^^

**Comment by SergeStinckwich** [comment] 2017-07-28 10:04
Ok don't forget to put the ready label and tell me the version to integrate.

**Comment by SergeStinckwich** [comment] 2017-07-28 10:05
Done, tests are green. Integrated in Kendrick-SergeStinckwich.629

**Closed by SergeStinckwich** 2017-07-28 10:05 UTC
Labels: ready
